In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [2]:
df=pd.read_csv('raw.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group D,master's degree,standard,none,62,70,75
1,female,group C,bachelor's degree,free/reduced,completed,66,83,83
2,female,group D,some college,free/reduced,none,79,89,86
3,male,group C,master's degree,free/reduced,none,61,67,66
4,male,group E,high school,standard,none,73,64,57

In [4]:
x=df.drop(['math_score'],axis=1)
y=df['math_score']

In [5]:
# column transformer
num_features = x.select_dtypes(exclude="object").columns
cat_features = x.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

num_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
    ("StandardScaler",num_transformer,num_features),
    ("OneHotEncoder",cat_transformer,cat_features),
    ]
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_3040\3585373526.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = x.select_dtypes(include="object").columns

In [6]:
x=preprocessor.fit_transform(x)
x.shape

(1000, 19)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((800, 19), (200, 19))

In [8]:
def evaluate_function(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(true, predicted)
    
    return mae, rmse, r2

In [9]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_function(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_function(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 5.3984
- Mean Absolute Error: 4.2968
- R2 Score: 0.8773
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.0640
- Mean Absolute Error: 4.0539
- R2 Score: 0.8708
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.6595
- Mean Absolute Error: 5.2600
- R2 Score: 0.8133
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.9043
- Mean Absolute Error: 4.6670
- R2 Score: 0.8244
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 5.3987
- Mean Absolute Error: 4.2953
- R2 Score: 0.8773
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.0617
- Mean Absolute Error: 4.0536
- R2 Score: 0.8709
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 5.9301
- Mean Absolute Error: 4.6967
- R2 Score: 0.8519
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.7277
- Mean Absolute Error: 5.3600
- R2 Score: 0.7720
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.4330
- Mean Absolute Error: 0.0325
- R2 Score: 0.9992
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 8.0387
- Mean Absolute Error: 6.4300
- R2 Score: 0.6745
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 2.3935
- Mean Absolute Error: 1.8872
- R2 Score: 0.9759
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.8238
- Mean Absolute Error: 4.6700
- R2 Score: 0.8291
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 1.0203
- Mean Absolute Error: 0.6601
- R2 Score: 0.9956
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.3890
- Mean Absolute Error: 5.0038
- R2 Score: 0.7944
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 3.0842
- Mean Absolute Error: 2.4068
- R2 Score: 0.9599
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.6409
- Mean Absolute Error: 4.5216
- R2 Score: 0.8397
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 5.8674
- Mean Absolute Error: 4.8359
- R2 Score: 0.8550
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0752
- Mean Absolute Error: 4.7421
- R2 Score: 0.8141
===================================

In [10]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
2                    Ridge  0.870932
0        Linear Regression  0.870813
7    CatBoosting Regressor  0.839700
5  Random Forest Regressor  0.829141
1                    Lasso  0.824384
8       AdaBoost Regressor  0.814072
6             XGBRegressor  0.794364
3    K-Neighbors Regressor  0.771984
4            Decision Tree  0.674467